services:
  website:
    build:
      context: ../website
      dockerfile: Dockerfile
    container_name: website
    environment:
      - API_URL=http://main-service:8000
    ports:
      - "3000:3000"
    networks:
      - main-network
    depends_on:
      - main-service
    profiles: ["web"]
    restart: unless-stopped
